### ISSUE TITLE
Self combine error on patch2

### ISSUE THREAD

**Issue by ForteDexe** [Mutcholoko/Haptic-Feedback-Linux#3]
I have this issue when applying the patch2, do you know how to fix it ?, I am using fedora 38
![image](https://github.com/Mutcholoko/Haptic-Feedback-Linux/assets/57673412/8f093d3c-66e6-4b97-839f-f698d0aff899)

I am currently using udev rule method with proton GE 8.4, but only the trigger work. TLOU is showing this in game
![image](https://github.com/Mutcholoko/Haptic-Feedback-Linux/assets/57673412/6e5d7e99-36d7-4ae2-b0c7-56b9e636b098)

**Comment by chenxiaolong** [comment]
For Proton 8.x, you should only need patch3. The first two patches were already merged into Wine/Proton (more details in #2).

**Comment by Mutcholoko** [comment]
>I have this issue when applying the patch2

Just like @chenxiaolong said, you don't need patches 1 and 2 anymore, only patch 3.

> I am currently using udev rule method

This is not needed anymore. In fact, I don't think this was ever needed.

>but only the trigger work

Triggers and speaker sounds worked from day-one iirc, so this is expected and has nothing to do with the patches you applied. 

Also, building this on Fedora is kind of a pain in the arse (I use Fedora too lol) if you don't disable SELinux. I'm trying to build it right now, and if I succeed, I'll make a new release here.

**Comment by Mutcholoko** [comment]
Patch 2 is not needed anymore as @chenxiaolong mentioned, so I'm closing this.

**Comment by Mutcholoko** [comment]
Only a small update here: patches 1 & 3 are currently needed, only patch 2 isn't.

**Comment by chenxiaolong** [comment]
> Only a small update here: patches 1 & 3 are currently needed, only patch 2 isn't.

Interesting. I've been playing Uncharted with patch 3 only. I'm using the `experimental_8.0` proton branch though, not `proton_8.0`. I haven't checked if the wine submodule is different between those.

> Also, building this on Fedora is kind of a pain in the arse (I use Fedora too lol) if you don't disable SELinux. I'm trying to build it right now, and if I succeed, I'll make a new release here.

I also use Fedora :slightly_smiling_face: I've been building with SELinux enabled by applying this patch:

```diff
diff --git a/Makefile b/Makefile
index 30289bca..e6979a52 100644
--- a/Makefile
+++ b/Makefile
@@ -57,6 +57,8 @@ ifneq ($(enable_ccache),0)
     CONFIGURE_CMD += --enable-ccache
 endif
 
+CONFIGURE_CMD += --relabel-volumes
+
 TOPLEVELGOALS := all any clean configure deploy downloads help install module proton protonsdk redist
 CONTAINERGOALS := $(filter-out $(TOPLEVELGOALS),$(MAKECMDGOALS))
 CONTAINERGOALS := $(filter-out $(BUILD_ROOT)/%,$(CONTAINERGOALS))
```

and then running:

```bash
CARGO_HOME=$(pwd)/cargo CCACHE_DIR=$(pwd)/ccache make install
```

The build process mounts the cargo, ccache, and proton directories into the container. Only those directories will be relabeled to the `system_u:object_r:container_file_t:s0:c###,c###` label. Since `CARGO_HOME` and `CCACHE_DIR` are overridden, it won't mess up the SELinux labels on `~/.cargo` or `~/.cache/ccache`/`~/.ccache` in the home directory.

**Comment by Mutcholoko** [comment]
Thanks for your tip!
Now I'll certainly be able to make much more builds! It was honestly a hassle to disable SELinux every single time I'd want to test/build this lol

>I also use Fedora

The best distro out there!
